---
- name: Add Kibana repo
  template:
    src: kibana.repo.j2
    dest: /etc/yum.repos.d/kibana.repo
    mode: 0644
    owner: root
    group: root

- name: Install Kibana
  yum:
    name: kibana
    state: latest

- name: Start Kibana
  service:
    name: kibana
    state: started
    enabled: true
