---
- name: Add Elasticsearch repo
  template:
    src: elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: 0644
    owner: root
    group: root

- name: Install Elasticsearch
  yum:
    name: elasticsearch
    state: latest

- name: get installed Elasticsearch plugins list
  command: "bin/plugin list chdir=/usr/share/elasticsearch"
  changed_when: false
  register: es_installed_plugins

- name: install Elasticsearch kopf plugin
  command: "bin/plugin install lmenezes/elasticsearch-kopf/2.x chdir=/usr/share/elasticsearch"
  when: "'- kopf' not in es_installed_plugins.stdout"

- name: install Elasticsearch mapper-attachments plugin
  command: "bin/plugin install mapper-attachments chdir=/usr/share/elasticsearch"
  when: "'- mapper-attachments' not in es_installed_plugins.stdout"

- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: true
