---
- name: Add gpg key rvm
  shell: curl -sSL https://rvm.io/mpapis.asc | sudo gpg2 --import -

- name: Install rvm
  shell: curl -L get.rvm.io | bash -s stable

- name: Execute rvm profile and ruby 2.1.4
  shell: source  /etc/profile.d/rvm.sh && rvm install 2.1.4 && gem install capistrano -v 2.15.9
            && gem install railsless-deploy && gem install capistrano-ext
  args:
    executable: /bin/bash
